/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class AttendeeEventDetailsResponse implements Serializable {


    @ColumnAlias("eventname")
    private String eventname;

    @ColumnAlias("eventdetails")
    private String eventdetails;

    @ColumnAlias("eventdate")
    private Date eventdate;

    @ColumnAlias("eventtime")
    private Time eventtime;

    @ColumnAlias("venuename")
    private String venuename;

    @ColumnAlias("addressline1")
    private String addressline1;

    @ColumnAlias("city")
    private String city;

    @ColumnAlias("province")
    private String province;

    @ColumnAlias("zipcode")
    private String zipcode;

    @ColumnAlias("country")
    private String country;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("phone")
    private String phone;

    @ColumnAlias("status")
    private Boolean status;

    @ColumnAlias("eventtype")
    private String eventtype;

    @ColumnAlias("eventURL")
    private String eventUrl;

    @ColumnAlias("button")
    private String button;

    @ColumnAlias("next_status")
    private String nextStatus;

    @ColumnAlias("includerow")
    private Long includerow;

    public String getEventname() {
        return this.eventname;
    }

    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    public String getEventdetails() {
        return this.eventdetails;
    }

    public void setEventdetails(String eventdetails) {
        this.eventdetails = eventdetails;
    }

    public Date getEventdate() {
        return this.eventdate;
    }

    public void setEventdate(Date eventdate) {
        this.eventdate = eventdate;
    }

    public Time getEventtime() {
        return this.eventtime;
    }

    public void setEventtime(Time eventtime) {
        this.eventtime = eventtime;
    }

    public String getVenuename() {
        return this.venuename;
    }

    public void setVenuename(String venuename) {
        this.venuename = venuename;
    }

    public String getAddressline1() {
        return this.addressline1;
    }

    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getEventtype() {
        return this.eventtype;
    }

    public void setEventtype(String eventtype) {
        this.eventtype = eventtype;
    }

    public String getEventUrl() {
        return this.eventUrl;
    }

    public void setEventUrl(String eventUrl) {
        this.eventUrl = eventUrl;
    }

    public String getButton() {
        return this.button;
    }

    public void setButton(String button) {
        this.button = button;
    }

    public String getNextStatus() {
        return this.nextStatus;
    }

    public void setNextStatus(String nextStatus) {
        this.nextStatus = nextStatus;
    }

    public Long getIncluderow() {
        return this.includerow;
    }

    public void setIncluderow(Long includerow) {
        this.includerow = includerow;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AttendeeEventDetailsResponse)) return false;
        final AttendeeEventDetailsResponse attendeeEventDetailsResponse = (AttendeeEventDetailsResponse) o;
        return Objects.equals(getEventname(), attendeeEventDetailsResponse.getEventname()) &&
                Objects.equals(getEventdetails(), attendeeEventDetailsResponse.getEventdetails()) &&
                Objects.equals(getEventdate(), attendeeEventDetailsResponse.getEventdate()) &&
                Objects.equals(getEventtime(), attendeeEventDetailsResponse.getEventtime()) &&
                Objects.equals(getVenuename(), attendeeEventDetailsResponse.getVenuename()) &&
                Objects.equals(getAddressline1(), attendeeEventDetailsResponse.getAddressline1()) &&
                Objects.equals(getCity(), attendeeEventDetailsResponse.getCity()) &&
                Objects.equals(getProvince(), attendeeEventDetailsResponse.getProvince()) &&
                Objects.equals(getZipcode(), attendeeEventDetailsResponse.getZipcode()) &&
                Objects.equals(getCountry(), attendeeEventDetailsResponse.getCountry()) &&
                Objects.equals(getEmail(), attendeeEventDetailsResponse.getEmail()) &&
                Objects.equals(getPhone(), attendeeEventDetailsResponse.getPhone()) &&
                Objects.equals(getStatus(), attendeeEventDetailsResponse.getStatus()) &&
                Objects.equals(getEventtype(), attendeeEventDetailsResponse.getEventtype()) &&
                Objects.equals(getEventUrl(), attendeeEventDetailsResponse.getEventUrl()) &&
                Objects.equals(getButton(), attendeeEventDetailsResponse.getButton()) &&
                Objects.equals(getNextStatus(), attendeeEventDetailsResponse.getNextStatus()) &&
                Objects.equals(getIncluderow(), attendeeEventDetailsResponse.getIncluderow());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEventname(),
                getEventdetails(),
                getEventdate(),
                getEventtime(),
                getVenuename(),
                getAddressline1(),
                getCity(),
                getProvince(),
                getZipcode(),
                getCountry(),
                getEmail(),
                getPhone(),
                getStatus(),
                getEventtype(),
                getEventUrl(),
                getButton(),
                getNextStatus(),
                getIncluderow());
    }
}