/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EventParticipantsResponse implements Serializable {


    @ColumnAlias("email")
    private String email;

    @ColumnAlias("status")
    private Boolean status;

    @ColumnAlias("eventname")
    private String eventname;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    @ColumnAlias("attended")
    private Boolean attended;

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getStatus() {
        return this.status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    public String getEventname() {
        return this.eventname;
    }

    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Boolean getAttended() {
        return this.attended;
    }

    public void setAttended(Boolean attended) {
        this.attended = attended;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EventParticipantsResponse)) return false;
        final EventParticipantsResponse eventParticipantsResponse = (EventParticipantsResponse) o;
        return Objects.equals(getEmail(), eventParticipantsResponse.getEmail()) &&
                Objects.equals(getStatus(), eventParticipantsResponse.getStatus()) &&
                Objects.equals(getEventname(), eventParticipantsResponse.getEventname()) &&
                Objects.equals(getFirstname(), eventParticipantsResponse.getFirstname()) &&
                Objects.equals(getLastname(), eventParticipantsResponse.getLastname()) &&
                Objects.equals(getAttended(), eventParticipantsResponse.getAttended());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmail(),
                getStatus(),
                getEventname(),
                getFirstname(),
                getLastname(),
                getAttended());
    }
}