/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.sql.Time;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class EventDetailsResponse implements Serializable {


    @ColumnAlias("eventname")
    private String eventname;

    @ColumnAlias("eventdate")
    private Date eventdate;

    @ColumnAlias("eventtime")
    private Time eventtime;

    @ColumnAlias("eventdetails")
    private String eventdetails;

    @ColumnAlias("venuename")
    private String venuename;

    @ColumnAlias("addressline1")
    private String addressline1;

    @ColumnAlias("city")
    private String city;

    @ColumnAlias("province")
    private String province;

    @ColumnAlias("zipcode")
    private String zipcode;

    public String getEventname() {
        return this.eventname;
    }

    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    public Date getEventdate() {
        return this.eventdate;
    }

    public void setEventdate(Date eventdate) {
        this.eventdate = eventdate;
    }

    public Time getEventtime() {
        return this.eventtime;
    }

    public void setEventtime(Time eventtime) {
        this.eventtime = eventtime;
    }

    public String getEventdetails() {
        return this.eventdetails;
    }

    public void setEventdetails(String eventdetails) {
        this.eventdetails = eventdetails;
    }

    public String getVenuename() {
        return this.venuename;
    }

    public void setVenuename(String venuename) {
        this.venuename = venuename;
    }

    public String getAddressline1() {
        return this.addressline1;
    }

    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EventDetailsResponse)) return false;
        final EventDetailsResponse eventDetailsResponse = (EventDetailsResponse) o;
        return Objects.equals(getEventname(), eventDetailsResponse.getEventname()) &&
                Objects.equals(getEventdate(), eventDetailsResponse.getEventdate()) &&
                Objects.equals(getEventtime(), eventDetailsResponse.getEventtime()) &&
                Objects.equals(getEventdetails(), eventDetailsResponse.getEventdetails()) &&
                Objects.equals(getVenuename(), eventDetailsResponse.getVenuename()) &&
                Objects.equals(getAddressline1(), eventDetailsResponse.getAddressline1()) &&
                Objects.equals(getCity(), eventDetailsResponse.getCity()) &&
                Objects.equals(getProvince(), eventDetailsResponse.getProvince()) &&
                Objects.equals(getZipcode(), eventDetailsResponse.getZipcode());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEventname(),
                getEventdate(),
                getEventtime(),
                getEventdetails(),
                getVenuename(),
                getAddressline1(),
                getCity(),
                getProvince(),
                getZipcode());
    }
}