/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetOldPasswordResponse implements Serializable {


    @ColumnAlias("password")
    private String password;

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetOldPasswordResponse)) return false;
        final GetOldPasswordResponse getOldPasswordResponse = (GetOldPasswordResponse) o;
        return Objects.equals(getPassword(), getOldPasswordResponse.getPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPassword());
    }
}