/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetuserResponse implements Serializable {


    @ColumnAlias("email")
    private String email;

    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    @ColumnAlias("association")
    private String association;

    @ColumnAlias("yearof")
    private Short yearof;

    @ColumnAlias("phone")
    private String phone;

    @ColumnAlias("role")
    private String role;

    @ColumnAlias("password")
    private String password;

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getAssociation() {
        return this.association;
    }

    public void setAssociation(String association) {
        this.association = association;
    }

    public Short getYearof() {
        return this.yearof;
    }

    public void setYearof(Short yearof) {
        this.yearof = yearof;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetuserResponse)) return false;
        final GetuserResponse getuserResponse = (GetuserResponse) o;
        return Objects.equals(getEmail(), getuserResponse.getEmail()) &&
                Objects.equals(getFirstname(), getuserResponse.getFirstname()) &&
                Objects.equals(getLastname(), getuserResponse.getLastname()) &&
                Objects.equals(getAssociation(), getuserResponse.getAssociation()) &&
                Objects.equals(getYearof(), getuserResponse.getYearof()) &&
                Objects.equals(getPhone(), getuserResponse.getPhone()) &&
                Objects.equals(getRole(), getuserResponse.getRole()) &&
                Objects.equals(getPassword(), getuserResponse.getPassword());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmail(),
                getFirstname(),
                getLastname(),
                getAssociation(),
                getYearof(),
                getPhone(),
                getRole(),
                getPassword());
    }
}