/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class RegisteredAttendeesResponse implements Serializable {


    @ColumnAlias("firstname")
    private String firstname;

    @ColumnAlias("lastname")
    private String lastname;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("eventname")
    private String eventname;

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEventname() {
        return this.eventname;
    }

    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof RegisteredAttendeesResponse)) return false;
        final RegisteredAttendeesResponse registeredAttendeesResponse = (RegisteredAttendeesResponse) o;
        return Objects.equals(getFirstname(), registeredAttendeesResponse.getFirstname()) &&
                Objects.equals(getLastname(), registeredAttendeesResponse.getLastname()) &&
                Objects.equals(getEmail(), registeredAttendeesResponse.getEmail()) &&
                Objects.equals(getEventname(), registeredAttendeesResponse.getEventname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFirstname(),
                getLastname(),
                getEmail(),
                getEventname());
    }
}