/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateAttendeesRequest implements Serializable {


    @JsonProperty("attended")
    @NotNull
    private String attended;

    @JsonProperty("email")
    @NotNull
    private String email;

    @JsonProperty("eventname")
    @NotNull
    private String eventname;

    public String getAttended() {
        return this.attended;
    }

    public void setAttended(String attended) {
        this.attended = attended;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEventname() {
        return this.eventname;
    }

    public void setEventname(String eventname) {
        this.eventname = eventname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateAttendeesRequest)) return false;
        final UpdateAttendeesRequest updateAttendeesRequest = (UpdateAttendeesRequest) o;
        return Objects.equals(getAttended(), updateAttendeesRequest.getAttended()) &&
                Objects.equals(getEmail(), updateAttendeesRequest.getEmail()) &&
                Objects.equals(getEventname(), updateAttendeesRequest.getEventname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAttended(),
                getEmail(),
                getEventname());
    }
}