/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdatePasswordRequest implements Serializable {


    @JsonProperty("newpassword")
    @NotNull
    private String newpassword;

    @JsonProperty("email")
    @NotNull
    private String email;

    public String getNewpassword() {
        return this.newpassword;
    }

    public void setNewpassword(String newpassword) {
        this.newpassword = newpassword;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdatePasswordRequest)) return false;
        final UpdatePasswordRequest updatePasswordRequest = (UpdatePasswordRequest) o;
        return Objects.equals(getNewpassword(), updatePasswordRequest.getNewpassword()) &&
                Objects.equals(getEmail(), updatePasswordRequest.getEmail());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getNewpassword(),
                getEmail());
    }
}