/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ValidateUserResponse implements Serializable {


    @ColumnAlias("emailaddress")
    private String emailaddress;

    public String getEmailaddress() {
        return this.emailaddress;
    }

    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ValidateUserResponse)) return false;
        final ValidateUserResponse validateUserResponse = (ValidateUserResponse) o;
        return Objects.equals(getEmailaddress(), validateUserResponse.getEmailaddress());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmailaddress());
    }
}