/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.vcalumni.vcadb_users.Events;

/**
 * Service object for domain model class {@link Events}.
 */
public interface EventsService {

    /**
     * Creates a new Events. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Events if any.
     *
     * @param events Details of the Events to be created; value cannot be null.
     * @return The newly created Events.
     */
    Events create(@Valid Events events);


	/**
     * Returns Events by given id if exists.
     *
     * @param eventsId The id of the Events to get; value cannot be null.
     * @return Events associated with the given eventsId.
	 * @throws EntityNotFoundException If no Events is found.
     */
    Events getById(String eventsId);

    /**
     * Find and return the Events by given id if exists, returns null otherwise.
     *
     * @param eventsId The id of the Events to get; value cannot be null.
     * @return Events associated with the given eventsId.
     */
    Events findById(String eventsId);

	/**
     * Find and return the list of Events by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param eventsIds The id's of the Events to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Events associated with the given eventsIds.
     */
    List<Events> findByMultipleIds(List<String> eventsIds, boolean orderedReturn);


    /**
     * Updates the details of an existing Events. It replaces all fields of the existing Events with the given events.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Events if any.
     *
     * @param events The details of the Events to be updated; value cannot be null.
     * @return The updated Events.
     * @throws EntityNotFoundException if no Events is found with given input.
     */
    Events update(@Valid Events events);

    /**
     * Deletes an existing Events with the given id.
     *
     * @param eventsId The id of the Events to be deleted; value cannot be null.
     * @return The deleted Events.
     * @throws EntityNotFoundException if no Events found with the given id.
     */
    Events delete(String eventsId);

    /**
     * Deletes an existing Events with the given object.
     *
     * @param events The instance of the Events to be deleted; value cannot be null.
     */
    void delete(Events events);

    /**
     * Find all Events matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Events.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Events> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Events matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Events.
     *
     * @see Pageable
     * @see Page
     */
    Page<Events> findAll(String query, Pageable pageable);

    /**
     * Exports all Events matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Events matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Events in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Events.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}