/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.vcalumni.vcadb_users.models.procedure.AddAttendeeRequest;
import com.vcalumni.vcadb_users.models.procedure.AddAttendeesRequest;
import com.vcalumni.vcadb_users.models.procedure.AddNewUserEventsRequest;

public interface VCADB_usersProcedureExecutorService {

    Void executeChange_attendee(String emailId, String eventId, String actionId);

    Void executeAdd_attendees(AddAttendeesRequest addAttendeesRequest);

    Void executeAdd_attendee(AddAttendeeRequest addAttendeeRequest);

    Void executeAdd_new_user_events(AddNewUserEventsRequest addNewUserEventsRequest);

}