/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.vcalumni.vcadb_users.models.query.*;

public interface VCADB_usersQueryExecutorService {

    Page<RegisteredAttendeesResponse> executeRegisteredAttendees(String eventId, Pageable pageable);

    void exportRegisteredAttendees(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EventsListResponse> executeEventsList(String eventtype, Pageable pageable);

    void exportEventsList(String eventtype, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<AttendeeEventDetailsResponse> executeAttendeeEventDetails(String email, String eventname, Pageable pageable);

    void exportAttendeeEventDetails(String email, String eventname, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetuserResponse> executeGetuser(String email, Pageable pageable);

    void exportGetuser(String email, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EventParticipantsResponse> executeEventParticipants(String eventname, Pageable pageable);

    void exportEventParticipants(String eventname, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Integer executeUpdateAttendees(UpdateAttendeesRequest updateAttendeesRequest);

    Page<EventDetailsResponse> executeEventDetails(String eventId, Pageable pageable);

    void exportEventDetails(String eventId, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}