/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.vcalumni.vcadb_users.models.procedure.AddAttendeeRequest;

public interface VCADB_usersProcedureExecutorService {

    Void executeAdd_attendee(AddAttendeeRequest addAttendeeRequest);

    Void executeChange_attendee(String emailId, String eventId, String actionId);

}