/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AddAttendeeRequest implements Serializable {


    @JsonProperty("email_id")
    @NotNull
    private String emailId;

    @JsonProperty("event_id")
    @NotNull
    private String eventId;

    @JsonProperty("action_id")
    @NotNull
    private String actionId;

    public String getEmailId() {
        return this.emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getEventId() {
        return this.eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String getActionId() {
        return this.actionId;
    }

    public void setActionId(String actionId) {
        this.actionId = actionId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AddAttendeeRequest)) return false;
        final AddAttendeeRequest addAttendeeRequest = (AddAttendeeRequest) o;
        return Objects.equals(getEmailId(), addAttendeeRequest.getEmailId()) &&
                Objects.equals(getEventId(), addAttendeeRequest.getEventId()) &&
                Objects.equals(getActionId(), addAttendeeRequest.getActionId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEmailId(),
                getEventId(),
                getActionId());
    }
}