/*Copyright (c) 2018-2019 rubaya.io All Rights Reserved.
 This software is the confidential and proprietary information of rubaya.io You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with rubaya.io*/
package com.vcalumni.vcadb_users;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Eventtype generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`eventtype`")
public class Eventtype implements Serializable {

    private String eventtype;
    private int id;

    @Id
    @Column(name = "`eventtype`", nullable = false, length = 255)
    public String getEventtype() {
        return this.eventtype;
    }

    public void setEventtype(String eventtype) {
        this.eventtype = eventtype;
    }

    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Eventtype)) return false;
        final Eventtype eventtypeInstance = (Eventtype) o;
        return Objects.equals(getEventtype(), eventtypeInstance.getEventtype());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEventtype());
    }
}